# Generated by Django 5.1.4 on 2025-01-09 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_union.mainmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('main', 'value'), name='secondary_uniq')],
            },
        ),
    ]
