name: Tests

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  runtest-backend:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: library/postgres:alpine
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
        cache-dependency-path: requirements.txt
    - name: Install binary dependencies
      run: |
        sudo apt update
        sudo apt install -y postgresql-client
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: |
        ./manage.py test --keepdb